### ISSUE TITLE
Running Hyperspace with Databricks Runtime 5.5 LTS / 6.4 results in ClassCastException

### ISSUE THREAD

**Issue by andrei-ionescu** [microsoft/hyperspace#302]
### Describe the issue

Running Hyperspace with Databricks Runtime 5.5 LTS, 6.4 and older is resulting in the following error:

```
java.lang.ClassCastException: org.apache.spark.sql.execution.datasources.SerializableFileStatus cannot be cast to org.apache.hadoop.fs.FileStatus at 
  com.microsoft.hyperspace.index.sources.default.DefaultFileBasedSource$$anonfun$3.apply(DefaultFileBasedSource.scala:134) at 
  scala.math.Ordering$$anon$5.compare(Ordering.scala:122) at 
  java.util.TimSort.countRunAndMakeAscending(TimSort.java:355) at java.util.TimSort.sort(TimSort.java:220) at 
  java.util.Arrays.sort(Arrays.java:1438) at scala.collection.SeqLike$class.sorted(SeqLike.scala:648) at 
  scala.collection.AbstractSeq.sorted(Seq.scala:41) at scala.collection.SeqLike$class.sortBy(SeqLike.scala:623) at 
  scala.collection.AbstractSeq.sortBy(Seq.scala:41) at 
  com.microsoft.hyperspace.index.sources.default.DefaultFileBasedSource.signature(DefaultFileBasedSource.scala:134) at 
  com.microsoft.hyperspace.index.sources.FileBasedSourceProviderManager$$anonfun$signature$1.apply(FileBasedSourceProviderManager.scala:80) at 
  com.microsoft.hyperspace.index.sources.FileBasedSourceProviderManager$$anonfun$signature$1.apply(FileBasedSourceProviderManager.scala:80) at 
  com.microsoft.hyperspace.index.sources.FileBasedSourceProviderManager$$anonfun$run$1.apply(FileBasedSourceProviderManager.scala:97) at 
  com.microsoft.hyperspace.index.sources.FileBasedSourceProviderManager$$anonfun$run$1.apply(FileBasedSourceProviderManager.scala:96) at scala.collection.IndexedSeqOptimized$class.foldl(IndexedSeqOptimized.scala:57) at 
  scala.collection.IndexedSeqOptimized$class.foldLeft(IndexedSeqOptimized.scala:66) at
  scala.collection.mutable.ArraySeq.foldLeft(ArraySeq.scala:46) at 
  com.microsoft.hyperspace.index.sources.FileBasedSourceProviderManager.run(FileBasedSourceProviderManager.scala:96) at 
  com.microsoft.hyperspace.index.sources.FileBasedSourceProviderManager.signature(FileBasedSourceProviderManager.scala:80) at 
  com.microsoft.hyperspace.index.FileBasedSignatureProvider$$anonfun$fingerprintVisitor$1.apply(FileBasedSignatureProvider.scala:53) at 
  com.microsoft.hyperspace.index.FileBasedSignatureProvider$$anonfun$fingerprintVisitor$1.apply(FileBasedSignatureProvider.scala:51)
```

### To Reproduce

1. Create a Databricks Cluster with 5.5 LTS Runtime
2. Import `hyperspace-core_2.11` in the library section as dependency
2. Create a notebook and attach it to the above cluster
3. Execute the code example from here: https://microsoft.github.io/hyperspace/#hyperspace-usage-api-in-apache-spark
4. When executing any `hs.createIndex` command the above `ClassCastException` is thrown.
5. No index is created due to exception.

### Expected behavior

Properly index creation.

### Environment 

Apache Spark 2.4.3
Databricks Runtime 5.5 LTS, 6.4

**Comment by andrei-ionescu** [comment]
Resolved by #303.
