### ISSUE TITLE
The `adl:/` and `abfss:/` protocols are not supported

### ISSUE THREAD

**Issue by andrei-ionescu** [microsoft/hyperspace#322]
### Describe the issue

The `adl:/` and `abfss:/` protocols are not supported by Hyperspace.

The error is this:

```
java.io.IOException: No FileSystem for scheme: adl
	at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:2660)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2667)
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:94)
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2703)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2685)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:373)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:295)
	at com.microsoft.hyperspace.util.PathUtils$.makeAbsolute(PathUtils.scala:26)
	at com.microsoft.hyperspace.util.PathUtils$.makeAbsolute(PathUtils.scala:23)
```

### To Reproduce

1. Have an ADL account
2. Write this code:

```
// ADLS Gen1
val tenant = "<tenant>"
val cid = "<client_id>"
val ck = "<client_key>"

val sharedProperties: Map[String, String] = Map(
    "dfs.adls.oauth2.access.token.provider.type" -> "ClientCredential",
    "fs.adl.oauth2.access.token.provider.type" -> "ClientCredential",
    "dfs.adls.oauth2.refresh.url" -> s"https://login.windows.net/$tenant/oauth2/token",
    "dfs.adls.oauth2.client.id" -> cid,
    "dfs.adls.oauth2.credential" -> ck,
    "fs.adl.oauth2.refresh.url" -> s"https://login.windows.net/$tenant/oauth2/token",
    "fs.adl.oauth2.client.id" -> cid,
    "fs.adl.oauth2.credential" -> ck
    "fs.abfss.impl" -> "org.apache.hadoop.fs.azurebfs.AzureBlobFileSystem",
    "fs.adl.impl" -> "org.apache.hadoop.fs.adl.AdlFileSystem"
)

sharedProperties.foreach { case (k, v) =>
  spark.conf.set(k, v)
  spark.sparkContext.hadoopConfiguration.set(k, v)
}

val dsPath = "adl://<account>.azuredatalakestore.net/dataset/ds1/"
val ds = spark.read.parquet(dsPath)

val hs = new Hyperspace(spark)

hs.createIndex(ds, IndexConfig("idx_id", indexedColumns = Seq("col1"), includedColumns = Seq("col2")))
```

3. It throws:

```
java.io.IOException: No FileSystem for scheme: adl
	at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:2660)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2667)
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:94)
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2703)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2685)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:373)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:295)
	at com.microsoft.hyperspace.util.PathUtils$.makeAbsolute(PathUtils.scala:26)
	at com.microsoft.hyperspace.util.PathUtils$.makeAbsolute(PathUtils.scala:23)
```

### Expected behavior

To be able to read data from the `adl:/` and `abfss:/` protocols by using the shared Spark context Hadoop configuration.

### Environment 

- Apache Spark 2.x
- Databricks Runtime 5.5 LTS

**Comment by andrei-ionescu** [comment]
I think I can easily fix it by using `spark.sessionState.newHadoopConf()` instead of the `new Configuration()` when running `getFileSystem` method.
