### ISSUE TITLE
JsonMappingException on index create and read

### ISSUE THREAD

**Issue by JNKHunter** [microsoft/hyperspace#373]
Following directions here: 
https://microsoft.github.io/hyperspace/docs/ug-quick-start-guide/

### Describe the issue
CreateIndex job completes but with error below. Subsequent access of indexes result in same error.
```
com.fasterxml.jackson.databind.JsonMappingException: Illegal character ((CTRL-CHAR, code 0)): only regular white space (\r, \n, \t) is allowed between tokens
```

### To Reproduce
```
val df = spark.read.parquet("path/to/parquet") //Creates dataframe with columns s,p,o
import com.microsoft.hyperspace._
val hs = new Hyperspace(spark)
import com.microsoft.hyperspace.index._
hs.createIndex(df, IndexConfig("index", indexedColumns = Seq("o","s"), includedColumns = Seq("p")))
```

Job starts and completes but with the following error:
 ```
JsonMappingExpection com.fasterxml.jackson.databind.JsonMappingException: Illegal character ((CTRL-CHAR, code 0)): only regular white space (\r, \n, \t) is allowed between tokens
```

Subsequent read of index fails with same error:
```
val indexes = hs.indexes
```
Produces
```
com.fasterxml.jackson.databind.JsonMappingException: Illegal character ((CTRL-CHAR, code 0)): only regular white space (\r, \n, \t) is allowed between tokens
```
### Expected behavior
Indexes should be readable and usable without JsonMappingException errors

### Environment 
OS: Linux RHEL
IDE: spark-shell
Apache Spark Version: 2.4.0
Platform: Cloudera CDH 6.3.3

**Comment by andrei-ionescu** [comment]
@JNKHunter Could you provide the parquet schema? 

You could do it with a command like this:

```
parquet-tools schema path/to/parquet
``` 

It would also be very helpful to have the following:
- full stack trace of the error
- a few example rows
- the version of the `jackson-databind` library that is loaded in Cloudera CDH

The exact steps that you followed in your Cloudera CDH 2.6.3 cluster, I did on my local machine and in Databricks cluster with  Runtime 5.5 and no issue there. 

It could be:

1. Character encoding issue due to unsupported char in some Spark actions
2. Library related error

We need more info from your side to have a better understanding of the cause.

**Comment by andrei-ionescu** [comment]
@JNKHunter Any updates on this ticket?

**Comment by mmuru-w** [comment]
I am getting the same exception. Here is the full stack trace.  
`
An error occurred while calling o87.createIndex.
: com.fasterxml.jackson.databind.JsonMappingException: Illegal character ((CTRL-CHAR, code 0)): only regular white space (\r, \n, \t) is allowed between tokens
 at [Source: (StringReader); line: 172, column: 19] (through reference chain: com.fasterxml.jackson.module.scala.deser.GenericMapFactoryDeserializerResolver$BuilderWrapper["content"]->com.fasterxml.jackson.module.scala.deser.GenericMapFactoryDeserializerResolver$BuilderWrapper["root"]->com.fasterxml.jackson.module.scala.deser.GenericMapFactoryDeserializerResolver$BuilderWrapper["subDirs"]->com.fasterxml.jackson.module.scala.deser.GenericFactoryDeserializerResolver$BuilderWrapper[0]->com.fasterxml.jackson.module.scala.deser.GenericMapFactoryDeserializerResolver$BuilderWrapper["subDirs"]->com.fasterxml.jackson.module.scala.deser.GenericFactoryDeserializerResolver$BuilderWrapper[0]->com.fasterxml.jackson.module.scala.deser.GenericMapFactoryDeserializerResolver$BuilderWrapper["subDirs"]->com.fasterxml.jackson.module.scala.deser.GenericFactoryDeserializerResolver$BuilderWrapper[0]->com.fasterxml.jackson.module.scala.deser.GenericMapFactoryDeserializerResolver$BuilderWrapper["subDirs"]->com.fasterxml.jackson.module.scala.deser.GenericFactoryDeserializerResolver$BuilderWrapper[0]->com.fasterxml.jackson.module.scala.deser.GenericMapFactoryDeserializerResolver$BuilderWrapper["subDirs"]->com.fasterxml.jackson.module.scala.deser.GenericFactoryDeserializerResolver$BuilderWrapper[0]->com.fasterxml.jackson.module.scala.deser.GenericMapFactoryDeserializerResolver$BuilderWrapper["files"]->com.fasterxml.jackson.module.scala.deser.GenericFactoryDeserializerResolver$BuilderWrapper[26])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:394)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:365)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:302)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
	at com.fasterxml.jackson.module.scala.deser.GenericFactoryDeserializerResolver$Deserializer.deserialize(GenericFactoryDeserializerResolver.scala:80)
	at com.fasterxml.jackson.module.scala.deser.UntypedObjectDeserializer.mapArray(UntypedObjectDeserializerModule.scala:37)
	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer.deserialize(UntypedObjectDeserializer.java:256)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringKeyMap(MapDeserializer.java:527)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:364)
	at com.fasterxml.jackson.module.scala.deser.GenericMapFactoryDeserializerResolver$Deserializer.deserialize(GenericMapFactoryDeserializerResolver.scala:71)
	at com.fasterxml.jackson.module.scala.deser.UntypedObjectDeserializer.mapObject(UntypedObjectDeserializerModule.scala:42)
	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer.deserialize(UntypedObjectDeserializer.java:248)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
	at com.fasterxml.jackson.module.scala.deser.GenericFactoryDeserializerResolver$Deserializer.deserialize(GenericFactoryDeserializerResolver.scala:80)
	at com.fasterxml.jackson.module.scala.deser.UntypedObjectDeserializer.mapArray(UntypedObjectDeserializerModule.scala:37)
	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer.deserialize(UntypedObjectDeserializer.java:256)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringKeyMap(MapDeserializer.java:527)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:364)
	at com.fasterxml.jackson.module.scala.deser.GenericMapFactoryDeserializerResolver$Deserializer.deserialize(GenericMapFactoryDeserializerResolver.scala:71)
	at com.fasterxml.jackson.module.scala.deser.UntypedObjectDeserializer.mapObject(UntypedObjectDeserializerModule.scala:42)
	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer.deserialize(UntypedObjectDeserializer.java:248)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
	at com.fasterxml.jackson.module.scala.deser.GenericFactoryDeserializerResolver$Deserializer.deserialize(GenericFactoryDeserializerResolver.scala:80)
	at com.fasterxml.jackson.module.scala.deser.UntypedObjectDeserializer.mapArray(UntypedObjectDeserializerModule.scala:37)
	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer.deserialize(UntypedObjectDeserializer.java:256)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringKeyMap(MapDeserializer.java:527)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:364)
	at com.fasterxml.jackson.module.scala.deser.GenericMapFactoryDeserializerResolver$Deserializer.deserialize(GenericMapFactoryDeserializerResolver.scala:71)
	at com.fasterxml.jackson.module.scala.deser.UntypedObjectDeserializer.mapObject(UntypedObjectDeserializerModule.scala:42)
	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer.deserialize(UntypedObjectDeserializer.java:248)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
	at com.fasterxml.jackson.module.scala.deser.GenericFactoryDeserializerResolver$Deserializer.deserialize(GenericFactoryDeserializerResolver.scala:80)
	at com.fasterxml.jackson.module.scala.deser.UntypedObjectDeserializer.mapArray(UntypedObjectDeserializerModule.scala:37)
	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer.deserialize(UntypedObjectDeserializer.java:256)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringKeyMap(MapDeserializer.java:527)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:364)
	at com.fasterxml.jackson.module.scala.deser.GenericMapFactoryDeserializerResolver$Deserializer.deserialize(GenericMapFactoryDeserializerResolver.scala:71)
	at com.fasterxml.jackson.module.scala.deser.UntypedObjectDeserializer.mapObject(UntypedObjectDeserializerModule.scala:42)
	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer.deserialize(UntypedObjectDeserializer.java:248)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
	at com.fasterxml.jackson.module.scala.deser.GenericFactoryDeserializerResolver$Deserializer.deserialize(GenericFactoryDeserializerResolver.scala:80)
	at com.fasterxml.jackson.module.scala.deser.UntypedObjectDeserializer.mapArray(UntypedObjectDeserializerModule.scala:37)
	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer.deserialize(UntypedObjectDeserializer.java:256)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringKeyMap(MapDeserializer.java:527)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:364)
	at com.fasterxml.jackson.module.scala.deser.GenericMapFactoryDeserializerResolver$Deserializer.deserialize(GenericMapFactoryDeserializerResolver.scala:71)
	at com.fasterxml.jackson.module.scala.deser.UntypedObjectDeserializer.mapObject(UntypedObjectDeserializerModule.scala:42)
	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer.deserialize(UntypedObjectDeserializer.java:248)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
	at com.fasterxml.jackson.module.scala.deser.GenericFactoryDeserializerResolver$Deserializer.deserialize(GenericFactoryDeserializerResolver.scala:80)
	at com.fasterxml.jackson.module.scala.deser.UntypedObjectDeserializer.mapArray(UntypedObjectDeserializerModule.scala:37)
	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer.deserialize(UntypedObjectDeserializer.java:256)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringKeyMap(MapDeserializer.java:527)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:364)
	at com.fasterxml.jackson.module.scala.deser.GenericMapFactoryDeserializerResolver$Deserializer.deserialize(GenericMapFactoryDeserializerResolver.scala:71)
	at com.fasterxml.jackson.module.scala.deser.UntypedObjectDeserializer.mapObject(UntypedObjectDeserializerModule.scala:42)
	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer.deserialize(UntypedObjectDeserializer.java:248)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringKeyMap(MapDeserializer.java:527)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:364)
	at com.fasterxml.jackson.module.scala.deser.GenericMapFactoryDeserializerResolver$Deserializer.deserialize(GenericMapFactoryDeserializerResolver.scala:71)
	at com.fasterxml.jackson.module.scala.deser.UntypedObjectDeserializer.mapObject(UntypedObjectDeserializerModule.scala:42)
	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer.deserialize(UntypedObjectDeserializer.java:248)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringKeyMap(MapDeserializer.java:527)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:364)
	at com.fasterxml.jackson.module.scala.deser.GenericMapFactoryDeserializerResolver$Deserializer.deserialize(GenericMapFactoryDeserializerResolver.scala:71)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4202)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3205)
	at com.fasterxml.jackson.hyperspace.module.scala.ScalaObjectMapper.readValue(ScalaObjectMapper.scala:211)
	at com.fasterxml.jackson.hyperspace.module.scala.ScalaObjectMapper.readValue$(ScalaObjectMapper.scala:210)
	at com.microsoft.hyperspace.util.JsonUtils$$anon$1.readValue(JsonUtils.scala:30)
	at com.microsoft.hyperspace.util.JsonUtils$.jsonToMap(JsonUtils.scala:43)
	at com.microsoft.hyperspace.index.LogEntry$.fromJson(LogEntry.scala:34)
	at com.microsoft.hyperspace.index.IndexLogManagerImpl.getLog(IndexLogManager.scala:75)
	at com.microsoft.hyperspace.index.IndexLogManagerImpl.getLog(IndexLogManager.scala:79)
	at com.microsoft.hyperspace.index.IndexLogManagerImpl.createLatestStableLog(IndexLogManager.scala:135)
	at com.microsoft.hyperspace.actions.Action.end(Action.scala:72)
	at com.microsoft.hyperspace.actions.Action.run(Action.scala:95)
	at com.microsoft.hyperspace.actions.Action.run$(Action.scala:84)
	at com.microsoft.hyperspace.actions.CreateAction.run(CreateAction.scala:29)
	at com.microsoft.hyperspace.index.IndexCollectionManager.create(IndexCollectionManager.scala:47)
	at com.microsoft.hyperspace.index.CachingIndexCollectionManager.create(CachingIndexCollectionManager.scala:78)
	at com.microsoft.hyperspace.Hyperspace.createIndex(Hyperspace.scala:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)

`

**Comment by rubybear** [comment]
I am having the exact same issue as @JNKHunter. 

I believe it has something to do with where the indexes are stored or how they are stored. In my case they are stored in /users/hive/warehouse/indexes.

hs.indexes returns the illegal character error. If I go ahead and delete my indexes hs.indexes returns an empty dataframe.

If I delete everything from /indexes and run the sample code I can successfully create and use indexes from sample data. But if I add an index from a data file into that directory then all of the indexes there are _corrupted_.

**Comment by sezruby** [comment]
Looks like this is the same issue of https://github.com/microsoft/hyperspace/discussions/431
I tried to reproduce the issue using PySpark and failed. It would be good if anyone can provide how to reproduce the error. 

Seems it's jackson compatibility issue as I succeeded to load the problematic index metadata file (under _hyperspace_log) on my local env. 

@clee704 Any idea? do you think your refactoring PR can resolve the issue?

**Comment by rubybear** [comment]
I can provide the _hyperspace_log for my test case if that helps. 

> Spark =>  version 2.4.0-cdh6.2.0
> Java Version => 1.8.0_282 (Red Hat, Inc.)
> Java Home => java-1.8.0-openjdk-1.8.0.282.b08-1.el7_9.x86_64/
> Scala Version => version 2.11.12
> CDH-6.2.0-1.cdh6.2.0.p0.967373

sampleData:

> +----------------------------------------+----------------------------------------+
> |i_key                                   |h_key                                   |
> +----------------------------------------+----------------------------------------+
> |e921b2c4df226b791e960276dcfecbbcad4be623|089ed13936cd4dabd9576f24884e5eff81b181b3|
> |e0d9a05af82f3402dd1bc288e0ffb45b39766946|c507be18b35bdb0a3681967ea428b309b85c794d|
> |3c080903bf0af58adb303fd5d85aaaf7b97c55f4|fdade8944fd5c8335734bdbcbc79b12c94457501|
> +----------------------------------------+----------------------------------------+

```
import org.apache.spark.sql._
import com.microsoft.hyperspace._
import com.microsoft.hyperspace.index._

import com.microsoft.hyperspace._

val sampleData = spark.read.parquet("/tmp/hyperspace_sample")

val hs = new Hyperspace(spark)

hs.createIndex(sampleData, IndexConfig("test_case_index", indexedColumns = Seq("i_key"), includedColumns = Seq("h_key")))
```

Error:

> com.fasterxml.jackson.databind.JsonMappingException: Illegal character ((CTRL-CHAR, code 0)): only regular white space (\r, \n, \t) is allowed between tokens
 at [Source: (StringReader); line: 1331, column: 34] (through reference chain: com.fasterxml.jackson.module.scala.deser.GenericMapFactoryDeserializerResolver$BuilderWrapper["source"]->com.fasterxml.jackson.module.scala.deser.GenericMapFactoryDeserializerResolver$BuilderWrapper["plan"]->com.fasterxml.jackson.module.scala.deser.GenericMapFactoryDeserializerResolver$BuilderWrapper["properties"]->com.fasterxml.jackson.module.scala.deser.GenericMapFactoryDeserializerResolver$BuilderWrapper["relations"]->com.fasterxml.jackson.module.scala.deser.GenericFactoryDeserializerResolver$BuilderWrapper[0]->com.fasterxml.jackson.module.scala.deser.GenericMapFactoryDeserializerResolver$BuilderWrapper["data"]->com.fasterxml.jackson.module.scala.deser.GenericMapFactoryDeserializerResolver$BuilderWrapper["properties"]->com.fasterxml.jackson.module.scala.deser.GenericMapFactoryDeserializerResolver$BuilderWrapper["content"]->com.fasterxml.jackson.module.scala.deser.GenericMapFactoryDeserializerResolver$BuilderWrapper["root"]->com.fasterxml.jackson.module.scala.deser.GenericMapFactoryDeserializerResolver$BuilderWrapper["subDirs"]->com.fasterxml.jackson.module.scala.deser.GenericFactoryDeserializerResolver$BuilderWrapper[0]->com.fasterxml.jackson.module.scala.deser.GenericMapFactoryDeserializerResolver$BuilderWrapper["subDirs"]->com.fasterxml.jackson.module.scala.deser.GenericFactoryDeserializerResolver$BuilderWrapper[0]->com.fasterxml.jackson.module.scala.deser.GenericMapFactoryDeserializerResolver$BuilderWrapper["files"]->com.fasterxml.jackson.module.scala.deser.GenericFactoryDeserializerResolver$BuilderWrapper[52])

[hs_test_log.log](https://github.com/microsoft/hyperspace/files/6594300/hs_test_log.log)

**Comment by mmuru-w** [comment]
What version jackson-databind library is compatible with Hyperspace?

**Comment by rubybear** [comment]
Could this help figure out the issue we are having? 

https://github.com/elastic/elasticsearch-hadoop/issues/1198#issuecomment-429340442

**Comment by sezruby** [comment]
@alex-shchetkov Thanks a lot for providing the fix👍 

@JNKHunter @mmuru-w @rubybear 
Could you try with the fix when you have a chance and reopen the issue if it doesn't work?
Thank you all!

**Comment by rubybear** [comment]
I tested it and got the following error:

Cannot parse JSON in viewfs://hdfs_directory/hyperspace/indexes/index1/_hyperspace_log/1: Unexpected token (END_OBJECT), expected FIELD_NAME: missing property 'type' that is to contain type id  (for class com.microsoft.hyperspace.index.Index)
 at [Source: {
  "name" : "index1",
  "derivedDataset" : {
    "properties" : {
      "columns" : {
        "indexed" : [ "id" ],
        "included" : [ "name" ]
      },
      "schemaString" : "{\"type\":\"struct\",\"fields\":[{\"name\":\"id\",\"type\":\"integer\",\"nullable\":true,\"metadata\":{}},{\"name\":\"name\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}}]}",
      "numBuckets" : 200,
      "properties" : {
        "hasParquetAsSourceFormat" : "true"
      }
    },
    "kind" : "CoveringIndex",
    "kindAbbr" : "CI"
  }

**Comment by sezruby** [comment]
@rubybear The current master has a breaking change to support different index type; you need to remove the indexes previously built and create again.

**Comment by sezruby** [comment]
Could you delete the directory and try again? Seems the JSON is created with old Hyperspace version.

**Comment by rubybear** [comment]
Thank you that worked!
