### ISSUE TITLE
Unable to change hyperspace system path to a non-default file system

### ISSUE THREAD

**Issue by apoorvedave1** [microsoft/hyperspace#391]
### Describe the issue

Changing hyperspace location to non-default file system using ```"spark.hyperspace.system.path"``` fails for non-default file systems. This is reprodicible, for example, on a databricks cluster where dbfs is the default file system and user tries to set index root to wasb or abfs

### To Reproduce

1. Databricks cluster (dbfs file system)
2. spark.conf.set("spark.hyperspace.system.path", "wasb:// or abfs://"
3. hs.createIndex(..

```

java.io.IOException: No FileSystem for scheme: wasb
	at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:2660)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2667)
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:94)
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2703)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2685)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:373)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:295)
```

### Expected behavior

no error

### RCA
```
val pathStr = "wasb://" + blob + "@" + storageName + ".blob.core.windows.net/hyperspaceIndexes" 
val path = new Path(pathStr)
path.getFileSystem(new Configuration)              >> FAILS WITH THE ABOVE ERROR
path.getFileSystem(spark.sessionState.newHadoopConf())  >> WORKS FINE (also mentioned in this PR #327 
```
This issue happens in https://github.com/microsoft/hyperspace/blob/master/src/main/scala/com/microsoft/hyperspace/index/IndexLogEntry.scala#L197-L199
Need to replace ``` new Configuration``` with ```spark.sessionState.newHadoopConf()``` to make sure spark finds all file systems.

**Comment by apoorvedave1** [comment]
fix is same as #327
